### ISSUE TITLE
A potential new introduced bug due to misusing condition variable in goker/blocking/kubernetes/58107

### ISSUE THREAD

**Issue by user12031** [timmyyuan/gobench#18]
blocking position: https://github.com/timmyyuan/gobench/blob/master/gobench/goker/blocking/kubernetes/58107/kubernetes58107_test.go#L47
Because the cond.Signal() and cond.Wait() execute concurrently without control. In a situation, the cond.Signal() executes first, then the cond.Wait() executes in G1 or G2. In that case, there is no Signal() can awaken the Wait(), which will result in goroutine leak. Sometimes the precedure can run normally, but the bug is easy to be triggered as well. 

Possible intervening

```
/// main 						     G1                         	    G2	                         
/// ...						             ...			            ...
///startResourceQuotaController()                                                
///go resourceQuotaController.Run()                                              
///resourceQuotaController.HelperSignals() 											
/// rq.queue.Put()					 go rq.worker(rq.queue, "G1")()   go rq.worker(rq.missingUsageQueue, "G2")()                
/// rq.missingUsageQueue.Put()                           queue.Get()                      queue.Get()    
/// q.cond.Signal()		                                         
///                                                      q.cond.Wait()                    q.cond.Wait()

**Comment by timmyyuan** [comment]
Good catch, could you please provide a traceback to prove this bug?

**Comment by user12031** [comment]
> Good catch, could you please provide a traceback to prove this bug?

OK, Thank you for your reply. I have used goleak to trigger the bug. The bug is subtle, and not easy to be detected by a dynamic tools, sometimes the program can run normally and goleak will not detect the bug. But after I ran the program many times util the trigger sequence is executed. The bug can be detected successfully by goleak, the traceback is below.
```
=== RUN   TestKubernetes58107
  kubernetes58107_test.go:119: found unexpected goroutines:
  Goroutine 5 in state sync.Cond.Wait, with sync.runtime_notifyListWait on top of the stack:
        goroutine 5 [sync.Cond.Wait]:
        sync.runtime_notifyListWait(0xc0000b0650, 0x0)
        	/usr/local/go/src/runtime/sema.go:513 +0xf8
        sync.(*Cond).Wait(0xc0000b0640)
        	/usr/local/go/src/sync/cond.go:56 +0x99
        awesomeProject/src/testdata/gobench/src/goker/blocking/kubernetes/58107.(*Type).Get(0xc0000ac028)
        	/home/song2048/桌面/goProject/src/awesomeProject/src/testdata/gobench/src/goker/blocking/kubernetes/58107/kubernetes58107_test.go:48 +0x77
        awesomeProject/src/testdata/gobench/src/goker/blocking/kubernetes/58107.(*ResourceQuotaController).worker.func1(0x0)
        	/home/song2048/桌面/goProject/src/awesomeProject/src/testdata/gobench/src/goker/blocking/kubernetes/58107/kubernetes58107_test.go:65 +0x6f
        awesomeProject/src/testdata/gobench/src/goker/blocking/kubernetes/58107.(*ResourceQuotaController).worker.func2()
        	/home/song2048/桌面/goProject/src/awesomeProject/src/testdata/gobench/src/goker/blocking/kubernetes/58107/kubernetes58107_test.go:70 +0x32
        created by awesomeProject/src/testdata/gobench/src/goker/blocking/kubernetes/58107.(*ResourceQuotaController).Run
        	/home/song2048/桌面/goProject/src/awesomeProject/src/testdata/gobench/src/goker/blocking/kubernetes/58107/kubernetes58107_test.go:78 +0x6c
        
         Goroutine 6 in state sync.Cond.Wait, with sync.runtime_notifyListWait on top of the stack:
        goroutine 6 [sync.Cond.Wait]:
        sync.runtime_notifyListWait(0xc0000b0690, 0x0)
        	/usr/local/go/src/runtime/sema.go:513 +0xf8
        sync.(*Cond).Wait(0xc0000b0680)
        	/usr/local/go/src/sync/cond.go:56 +0x99
        awesomeProject/src/testdata/gobench/src/goker/blocking/kubernetes/58107.(*Type).Get(0xc0000ac030)
        	/home/song2048/桌面/goProject/src/awesomeProject/src/testdata/gobench/src/goker/blocking/kubernetes/58107/kubernetes58107_test.go:48 +0x77
        awesomeProject/src/testdata/gobench/src/goker/blocking/kubernetes/58107.(*ResourceQuotaController).worker.func1(0x0)
        	/home/song2048/桌面/goProject/src/awesomeProject/src/testdata/gobench/src/goker/blocking/kubernetes/58107/kubernetes58107_test.go:65 +0x6f
        awesomeProject/src/testdata/gobench/src/goker/blocking/kubernetes/58107.(*ResourceQuotaController).worker.func2()
        	/home/song2048/桌面/goProject/src/awesomeProject/src/testdata/gobench/src/goker/blocking/kubernetes/58107/kubernetes58107_test.go:70 +0x32
        created by awesomeProject/src/testdata/gobench/src/goker/blocking/kubernetes/58107.(*ResourceQuotaController).Run
        	/home/song2048/桌面/goProject/src/awesomeProject/src/testdata/gobench/src/goker/blocking/kubernetes/58107/kubernetes58107_test.go:79 +0xbb
        ]
--- FAIL: TestKubernetes58107 (0.46s)

FAIL`
```
And you can reproduce the bug easily by yourself to run the program many times util the trigger path is executed like this
![TWDLA1A% GD{YC( 7D)SB`N](https://github.com/timmyyuan/gobench/assets/61485003/d6106480-a4a1-4c22-855d-0bbe3942066d)

**Comment by timmyyuan** [comment]
Thank you for the detailed explanation, the relevant descriptions have been updated.
